runtime: go
api_version: go1

handlers:
- url: /(.*\.(gif|png|jpeg|jpg|css|js|ico))$
  static_files: dist/\1
  upload: dist/(.*)
- url: /manifest.json
  static_files: dist/manifest.json
  upload: dist/manifest.json
- url: /service-worker.js
  static_files: dist/service-worker.js
  upload: dist/service-worker.js
- url: /(.*)
  static_files: dist/index.html
  upload: dist/index.html
